# Развертывание Storybook на GitHub Pages
name: CD

on:
  # Ручной запуск развертывания
  workflow_dispatch:
    inputs:
      deploy_type:
        description: 'Тип развертывания'
        required: true
        default: 'storybook'
        type: choice
        options:
          - storybook
          - packages

  # Автоматический запуск после успешного завершения CI
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: ['main']

# Настройка разрешений для развертывания на Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешить только одно одновременное развертывание
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Развертывание Storybook
  deploy-storybook:
    # Условия запуска:
    # - ручной запуск
    # - автоматический после успешного CI
    if: (github.event_name == 'workflow_dispatch' && inputs.deploy_type == 'storybook') ||
      (github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.name == 'CI')

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      # Загрузка артефактов Storybook из CI
      - name: Загрузка артефактов Storybook
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: CI.yml
          name: storybook-artifacts
          path: ./storybook-static
          branch: main

      # GitHub Pages
      - name: Настройка GitHub Pages
        uses: actions/configure-pages@v5

      - name: Загрузка артефактов для развертывания
        uses: actions/upload-pages-artifact@v3
        with:
          path: './storybook-static'

      - name: Развертывание на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Развертывание пакетов (для будущего использования)
  deploy-packages:
    if: (github.event_name == 'workflow_dispatch' && inputs.deploy_type == 'packages')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      # Загрузка артефактов пакетов из CI
      - name: Загрузка артефактов пакетов
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: CI.yml
          name: packages-artifacts
          path: ./packages-dist
          branch: main

      - name: Публикация пакетов
        run: |
          echo "Здесь будет логика публикации пакетов в npm"
          echo "Пока что просто выводим информацию о собранных пакетах"
          ls -la ./packages-dist/
